name: Builds and tests - elrond-wasm-node

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rust_test:
    name: Cargo build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: nightly
      - name: Run rust tests
        run: cd elrond-wasm-node & cargo build
  clippy_check:
    name: Clippy linter check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            default: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args:
